baseURL: "https://tagomor.is/"
languageCode: "en-us"
title: "tagomoris: Satoshi Tagomori"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://tagomoris.hatenablog.com/
      weight: 1

params:
  title: "tagomoris"
  description: The profile page of Satoshi Tagomori a.k.a. tagomoris
  favicon: "/tagomoris-favicon.png"
  useBootstrapCDN: false
  animate: true
  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark
  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left
  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Satoshi Tagomori" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Software engineer, technical consultant, web/app developer"
    title: "Satoshi Tagomori"
    subtitle: "Web, Data Analytics, IT Infrastructure, and Apps"
    content: "田籠 聡 (Satoshi Tagomori), a.k.a. tagomoris, is working on Web Application, Data Analytics Infrastructure, IT Infrastructure and iOS App."
    image: /profile-2017.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/tagomoris
        - icon: fab fa-twitter
          url: https://twitter.com/tagomoris
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/satoshi-tagomori-80b41b21/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/tagomoris-2018.jpg"
    content: |-
      I am a programmer, technical consultant, OSS developer and an App service provider. The main technical focuses are developing/hosting/operating Web applications, building Data analytics platforms, developing data management/distributed middleware, and writing OSS libraries.

      As a technical consultant, I have some contracts with a few startup companies and providing my knowledges through consulting sessions about data engineering, system architecture, engineering team building, and generic problems at tech startups.

      My current focus is to build an App service and to ship it.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Data engineering"
        - "Distributed systems"
        - "Ruby"
        - "Swift"
        - "React"

  # # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  # Education
  education:
    enable: true
    title: "Customers, Services and Publications"
    index: false
    items:
      # - title: Pathtraq
      - title: Mentemo
        school:
          name: "Technical Consultant"
          url: "https://engineering.mentemo.com/entry/2021/10/20/100852"
        date: "2021 - Now"
        content: |-
          Consultation about everything around engineering and startups
            - Provide architecture reviews and system designs
            - Guide how to build the engineering team
            - Review system/performance troubles and suggest how to solve them
      - title: Loglass
        school:
          name: "Technical Consultant"
          url: "https://prtimes.jp/main/html/rd/p/000000050.000052025.html"
        date: "2021 - Now"
        content: |-
          Consultation about data engineering, database and system architecture
      - title: "Fluentd: Pragmatic Introduction (Fluentd実践入門)"
        school:
          name: "Author"
          url: "https://gihyo.jp/book/2022/978-4-297-13109-8"
        date: "2022"
        content: |-
          <img src="http://image.gihyo.co.jp/assets/images/cover/2022/9784297131098.jpg" alt="Fluentd実践入門" height="280" style="float: right;" />
          The world's first, definitive guide of the data collector software, Fluentd. Fluentd is a CNCF project, and a defacto standard tool to collect logs on the Kubernetes platform. I am one of main developers/maintainers of Fluentd, and this book was written based on my long-term experience and knowledges as a user and a developer of Fluentd.
          
          Thid book covers:
            - The overview of log collection and Fluentd use cases
            - How to install/configure Fluentd
            - How Fluentd processes data
            - What the Fluentd plugins are
            - How to operate Fluentd in production
            - How to write Fluentd plugins
        # featuredLink:
        #   enable: true
        #   name: "Description and Index in English"
        #   url: "https://example.com"

  # projects
  projects:
    enable: true
    title: "Events and OSS Projects"
    items:
      - title: ISUCON
        content: ISUCON is a performance tuning contest about Web applications. I founded ISUCON as a brand new event at 2011, and worked to prepare the contest at 2011 (ISUCON1), 2012 (ISUCON2) and 2015 (ISUCON5). And I was also a member of the winner team at 2013 (ISUCON3) and 2014 (ISUCON4). Now that event is organized by LINE corp. and has been taken over by many Japanese web app engineers.
        image: https://isucon.net/parts/logo.png
        featured:
          name: isucon.net
          link: https://isucon.net/
        badges:
          - "Web"
          - "Database"
          - "Infrastructure"
          - "Performance"

      - title: Fluentd
        content: Fluentd was founded originally by Sadayuki Furuhashi (@frsyuki), then I joined that project as a maintainer. I re-designed its plugin system and core plugins totally, then worked to make the stable version, v1.0. Fluentd is now a CNCF project.
        image: https://www.fluentd.org/images/miscellany/fluentd-logo.png
        featured:
          name: Fluentd Contributors
          link: https://github.com/fluent/fluentd/graphs/contributors
        badges:
          - "Big Data"
          - "Logging"
          - "Infrastructure"
        links:
          - icon: fab fa-github
            url: https://github.com/fluent/fluentd

      - title: Norikra
        content: Norikra is an OSS stream processing tool, written in JRuby, runs on JVM. I founded and developled Norikra to realize ease-to-use (non-distributed) stream processing using SQL in a schema-less way.
        image: https://raw.githubusercontent.com/norikra/norikra.github.io/master/images/norikra.background.png
        badges:
          - "JRuby"
          - "Stream Processing"
          - "Big Data"
          - "SQL"
        links:
          - icon: fab fa-github
            url: https://github.com/norikra/norikra

      - title: MessagePack
        content: MessagePack is an open source data serialization format project, and I joined this project as a maintainer. I worked on msgpack-ruby main maintainer, and a member of MessagePack spec maintainer team.
        image: https://raw.githubusercontent.com/msgpack/website/master/images/logo.png
        badges:
          - "Data"
          - "Ruby"
        links:
          - icon: fab fa-github
            url: https://github.com/msgpack/msgpack
          - icon: fab fa-github
            url: https://github.com/msgpack/msgpack-ruby

      - title: Woothee
        content: Woothee is a project to create/maintain multi-language user-agent string parser. I founded the project Woothee, and developed the main set of data/tests, then libraries in Java, Ruby, Perl, and JavaScript. Many other contributors joined this project, and many other language implementations were added.
        image: /woothee.png
        badges:
          - "Web"
          - "User-Agent"
          - "Java"
          - "Perl"
          - "Ruby"
          - "JavaScript"
        links:
          - icon: fab fa-github
            url: https://github.com/woothee/woothee

  # Achievements
  achievements:
    enable: true
    title: "Conference Talks and Interviews"
    items:
      - title: RubyKaigi Takeout 2021
        content: |
          RubyKaigi is an international conference about the programming language, Ruby. I presented a talk about a Ruby web application server using Ractor at RubyKaigi Takeout 2021. I also presented at RubyKaigi 2019 (Lightening talk), 2018, 2017, 2016, 2015, 2014 (Lightening talk), and 2013.
        url: https://rubykaigi.org/2021-takeout/presentations/tagomoris.html
      - title: RubyConf 2018
        content: |-
          RubyConf is another international Ruby conference in US. I presented a talk about meta programming technics in Ruby at RubyConf 2018. I also presented at RubyConf 2014.
        url: https://www.youtube.com/watch?v=ZPaxvU7dMBU
      - title: EURUKO 2015
        content: |-
          Euruko is an annual European Ruby Conference, and I presented a talk about data company's systems and architecture at Euruko 2015.
        url: https://2015.euruko.org/#speakers
      - title: YAPC::Asia 2015
        content: |-
          YAPC::Asia was a conference about a language Perl and other topics. I presented at YAPC::Asia 2015 about OSS calcutre and how to maintain OSS projects. I also presented at YAPC::Asia 2014.
        url: http://yapcasia.org/2015/talk/show/5f5cad74-004a-11e5-acf4-89c77d574c3a
      - title: HadoopCon 2014 Taiwan
        content: |-
          HadoopCon Taiwan is a conference about Hadoop, a distributed processing platform. I presented at there as a keynote speaker about Lambda architecture and an actual system in LINE, and also as a speaker about the OSS stream processing software, developed by myself, Norikra.
        url: http://2014.hadoopcon.org/agenda/
      - title: And Many Others...
        content: My talk presentations are hosted on my SlideShare page.
        url: https://www.slideshare.net/tagomoris/presentations

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: Email me, or send DM to me on Twitter.
    email: tagomoris@gmail.com
    btnName: tagomoris@gmail.com

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/tagomoris
      twitter: https://twitter.com/tagomoris
      linkedin: https://www.linkedin.com/in/satoshi-tagomori-80b41b21/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
