baseURL: "https://tagomor.is/"
languageCode: "en-us"
title: "tagomoris: Satoshi Tagomori"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://tagomoris.hatenablog.com/
      weight: 1

params:
  title: "tagomoris"
  description: The profile page of Satoshi Tagomori a.k.a. tagomoris
  favicon: "/tagomoris-favicon.png"
  useBootstrapCDN: false
  animate: true
  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark
  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left
  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Satoshi Tagomori" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Software engineer, technical consultant, web/app developer"
    title: "Satoshi Tagomori"
    subtitle: "Web, Data Analytics, IT Infrastructure, and Apps"
    content: "田籠 聡 (Satoshi Tagomori), a.k.a. tagomoris, is working on Web Application, Data Analytics Infrastructure, IT Infrastructure and iOS App."
    image: /profile-2017.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/tagomoris
        - icon: fab fa-twitter
          url: https://twitter.com/tagomoris
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/satoshi-tagomori-80b41b21/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/tagomoris-2018.jpg"
    content: |-
      I am a programmer, technical consultant, OSS developer and an App service provider. The main technical focuses are developing/hosting/operating Web applications, building Data analytics platforms, developing data management/distributed middleware, and writing OSS libraries.
      
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  # Education
  education:
    enable: true
    title: "Customers, Services and Publications"
    index: false
    items:
      # - title: Pathtraq
      - title: Mentemo
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: Loglass
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "Fluentd: Pragmatic Introduction"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Conference Talks and Interviews"
    items:
      - title: RubyKaigi
        content: Takeout 2021, 2019 (LT), 2018, ...
        url: https://example.com
      - title: RubyConf 2018
        content: And 2014
      - title: EURUKO 2015
        content: We are developed a product which can help others.
      - title: YAPC::Asia 2015
        content: And 2014
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: HadoopCon 2014 Taiwan
        content: Contributed to a open source project.
        url: https://example.com
      - title: And Many Others...
        content: My talk presentations are hosted on my SlideShare page.
        url: https://www.slideshare.net/tagomoris/presentations

  # projects
  projects:
    enable: true
    title: "Events and OSS Projects"
    items:
      - title: ISUCON
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

      - title: Fluentd
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Norikra
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

      - title: MessagePack
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        # image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Woothee
        content: A clean and simple Hugo template for personal portfolio and blog.
        # image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: Email me, or send DM to me on Twitter.
    email: tagomoris@gmail.com
    btnName: tagomoris@gmail.com

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/tagomoris
      twitter: https://twitter.com/tagomoris
      linkedin: https://www.linkedin.com/in/satoshi-tagomori-80b41b21/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
